[colors]
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 22

[font.bold]
family = "Iosevka"
style = "Bold"

[font.bold_italic]
family = "Iosevka"
style = "Bold Italic"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"
style = "Regular"

[mouse]
hide_when_typing = false

[window]
startup_mode = "Windowed"
decorations = "Transparent"
dynamic_title = false
opacity = 0.9
blur = true

[window.padding]
x = 4
y = 4
